// <auto-generated />
using System;
using HamperStore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamperStore.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807060857_InitialSQLiteCreate")]
    partial class InitialSQLiteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CityHamper", b =>
                {
                    b.Property<int>("AvailableCitiesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HampersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvailableCitiesId", "HampersId");

                    b.HasIndex("HampersId");

                    b.ToTable("HamperCityAvailability", (string)null);
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredCityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreferredCityId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Hamper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Hampers");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.HamperImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HamperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HamperId");

                    b.ToTable("HamperImages");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.HamperItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HamperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockNote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HamperId");

                    b.ToTable("HamperItems");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HamperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occasion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HamperId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.InquiryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HamperItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InquiryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HamperItemId");

                    b.HasIndex("InquiryId");

                    b.ToTable("InquiryItems");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InquiryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InquiryId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HamperId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HamperId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CityHamper", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("AvailableCitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamperStore.Core.Entities.Hamper", null)
                        .WithMany()
                        .HasForeignKey("HampersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Customer", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.City", "PreferredCity")
                        .WithMany()
                        .HasForeignKey("PreferredCityId");

                    b.Navigation("PreferredCity");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Hamper", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.Category", "Category")
                        .WithMany("Hampers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.HamperImage", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.Hamper", "Hamper")
                        .WithMany("Images")
                        .HasForeignKey("HamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hamper");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.HamperItem", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.Hamper", "Hamper")
                        .WithMany("Items")
                        .HasForeignKey("HamperId");

                    b.Navigation("Hamper");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Inquiry", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.City", "City")
                        .WithMany("Inquiries")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamperStore.Core.Entities.Customer", "Customer")
                        .WithMany("Inquiries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamperStore.Core.Entities.Hamper", "Hamper")
                        .WithMany()
                        .HasForeignKey("HamperId");

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("Hamper");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.InquiryItem", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.HamperItem", "HamperItem")
                        .WithMany("InquiryItems")
                        .HasForeignKey("HamperItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamperStore.Core.Entities.Inquiry", "Inquiry")
                        .WithMany("InquiryItems")
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HamperItem");

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Order", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.City", "City")
                        .WithMany("Orders")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamperStore.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamperStore.Core.Entities.Inquiry", "Inquiry")
                        .WithOne("Order")
                        .HasForeignKey("HamperStore.Core.Entities.Order", "InquiryId");

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("HamperStore.Core.Entities.Hamper", "Hamper")
                        .WithMany("OrderItems")
                        .HasForeignKey("HamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamperStore.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hamper");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Category", b =>
                {
                    b.Navigation("Hampers");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.City", b =>
                {
                    b.Navigation("Inquiries");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Customer", b =>
                {
                    b.Navigation("Inquiries");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Hamper", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Items");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.HamperItem", b =>
                {
                    b.Navigation("InquiryItems");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Inquiry", b =>
                {
                    b.Navigation("InquiryItems");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HamperStore.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
